apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: garlic-logs
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
      logMessageField: message
      logLevelField: level

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs: true
      serviceMapping:
        - name: auth-service
          datasource: Elasticsearch
        - name: product-service
          datasource: Elasticsearch
        - name: order-service
          datasource: Elasticsearch
        - name: inventory-service
          datasource: Elasticsearch
        - name: payment-service
          datasource: Elasticsearch
        - name: search-service
          datasource: Elasticsearch
        - name: notification-service
          datasource: Elasticsearch
